AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: fotopo

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python3.6
      CodeUri: ./lambda.py
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: any

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"

        basePath: "/Prod"

        schemes:
        - "https"

        info:
          version: "1.0"
          title: "fotopo"

        securityDefinitions:
          fotopo:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "cognito_user_pools"
            x-amazon-apigateway-authorizer:
              type: "cognito_user_pools"
              providerARNs:
              - !GetAtt UserPool.Arn

        paths:
          /:
            x-amazon-apigateway-any-method:
              responses: {}
              security:
              - fotopo: []
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !GetAtt Function.Arn
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
                passthroughBehavior: "when_no_match"
